global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["worker-node-1-ip:9100", "worker-node-2-ip:9100"]

  - job_name: "kubernetes-nodes"
    kubernetes_sd_configs:
      - role: node
