apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Ensure this matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80       # Exposed service port
      targetPort: 80 # Container port
  type: LoadBalancer  # Change to NodePort if not using cloud provider
